# Generated by Django 6.0.6 on 2026-06-12 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='ሙሉ ስም')),
                ('gender', models.CharField(choices=[('ሴት', 'ሴት'), ('ወንድ', 'ወንድ')], max_length=10, verbose_name='ጾታ')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(50)], verbose_name='ዕድሜ')),
                ('phone', models.CharField(max_length=15, verbose_name='የስልክ ቁጥር')),
                ('region', models.CharField(max_length=100, verbose_name='ያሉበት ክልል')),
                ('education', models.CharField(max_length=100, verbose_name='የትምህርት ደረጃ')),
                ('destination', models.CharField(choices=[('ሳውዲ አረቢያ', 'ሳውዲ አረቢያ'), ('ዱባይ', 'የተባበሩት አረብ ኤምሬትስ (ዱባይ)'), ('ኩዌት', 'ኩዌት'), ('ዮርዳኖስ', 'ዮርዳኖስ'), ('ኳታር', 'ኳታር')], max_length=100, verbose_name='መሄድ የሚፈልጉበት ሀገር')),
                ('job_type', models.CharField(choices=[('የቤት ውስጥ ሰራተኛ', 'የቤት ውስጥ ሰራተኛ'), ('አስተናጋጅ', 'አስተናጋጅ / ሆቴል ስራ'), ('ሹፌር', 'ሹፌር'), ('የጽዳት ሰራተኛ', 'የጽዳት ሰራተኛ'), ('ሌላ ሙያ', 'ሌላ ሙያ')], max_length=100, verbose_name='የሚፈልጉት የስራ አይነት')),
                ('has_experience', models.BooleanField(default=False, verbose_name='ቀደም ሲል በአረብ ሀገር ሰርተዋል?')),
                ('passport_status', models.CharField(choices=[('አለኝ - የታደሰ', 'አለኝ (የታደሰ/አዲስ)'), ('በሂደት ላይ ነው', 'በሂደት ላይ ነው'), ('የለኝም', 'የለኝም')], max_length=50, verbose_name='ፓስፖርት ሁኔታ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='ተጨማሪ አስተያየት')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='የተመዘገበበት ቀን')),
            ],
        ),
    ]
